baseURL = "https://rezigned.com"
languageCode = "en-us"
title = "@rezigned"
theme = "yinyang"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "dracula"
    tabWidth = 2

[author]
  name = "rezigned"
  homepage = "https://rezigned.com"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "EN"
    weight = 1
  [languages.th]
    contentDir = "content/th"
    languageName = "TH"
    weight = 2

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]
mainSections = ["posts"]
headTitle = "rezigned"
Description = "Code is art - âˆ€ğ‘¥ âˆˆ ğ‘ğ‘’ğ‘œğ‘ğ‘™ğ‘’, âˆƒğ‘¥ â™¡ Î»"
extraHead = ''
extraCSSFiles = ["css/main.css"]
ga = "UA-28430747-1"
# comments = '<script src="https://utteranc.es/client.js" repo="rezigned/rezigned.github.io" issue-term="pathname" label="comment" theme="github-light" crossorigin="anonymous" async></script>'
comments = '<script src="https://giscus.app/client.js" data-repo="rezigned/rezigned.github.io" data-repo-id="MDEwOlJlcG9zaXRvcnkyNDcyNjU1" data-category="General" data-category-id="DIC_kwDOACW6z84CBBq9" data-mapping="pathname" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="bottom" data-theme="light" data-lang="en" crossorigin="anonymous" async></script>'

[[params.socials]]
name = "About Me"
link = "https://twitter.com/rezigned"

[[params.socials]]
name = "Github"
link = "https://github.com/rezigned"
postHeaderContent = ""
postFooterContent = "<br/><br/><p>Subscribe toï¼š<a target='_blank' href='https://mailchi.mp/a1a0d59e7a19/joway'>Joway's Blog</a></p>"
